[project]
name = "streak-tracker"
description = "User streak tracker for wallet connections"
authors = []
telemetry = false
cache_dir = '.\.cache'
requirements = []

[contracts.streak-tracker]
path = 'contracts/streak-tracker.clar'
clarity_version = 2
epoch = '2.4'

[contracts.simple-counter]
path = 'contracts/simple-counter.clar'
clarity_version = 2
epoch = '2.4'

[repl]
costs_version = 2
parser_version = 2

[[accounts]]
name = "deployer"
mnemonic = "market stand keen rug glory net core ginger deposit sell lottery alone"
balance = 100000000000000

[[accounts]]
name = "wallet_1"
mnemonic = "sell lottery alone market stand keen rug glory net core ginger deposit"
balance = 100000000000000

[[accounts]]
name = "wallet_2"
mnemonic = "alone sell lottery market stand keen rug glory net core ginger deposit"
balance = 100000000000000

[network]
name = "devnet"

[devnet]
disable_bitcoin_explorer = true
disable_stacks_explorer = true
disable_stacks_api = true
bitcoin_controller_automining_disabled = false
orchestrator_port = 20443
bitcoin_node_p2p_port = 18444
bitcoin_node_rpc_port = 18443
stacks_node_p2p_port = 20444
stacks_node_rpc_port = 20443
stacks_api_port = 3999
bitcoin_explorer_port = 8001
stacks_explorer_port = 8000
bitcoin_controller_block_time = 60000
orchestrator_ingestion_port = 20445
pox_stacking_orders = []